# Generated by Django 2.2.2 on 2019-06-30 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('aid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=32)),
                ('content', models.TextField()),
                ('create_datetime', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('tid', models.AutoField(primary_key=True, serialize=False)),
                ('tag_name', models.CharField(max_length=18)),
            ],
        ),
        migrations.CreateModel(
            name='ArticlesToTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Articles')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Tags')),
            ],
        ),
    ]
