# Generated by Django 2.2.2 on 2019-08-25 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='imgs',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
