# Generated by Django 2.2.2 on 2019-08-22 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pwd', models.CharField(max_length=128)),
                ('fail_count', models.IntegerField()),
                ('lock_datetime', models.DateTimeField()),
            ],
        ),
    ]
