# Generated by Django 2.2.2 on 2019-08-22 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0002_auto_20190822_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adm',
            name='lock_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
