# Generated by Django 2.2.2 on 2019-08-22 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0003_auto_20190822_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='adm',
            name='is_locked',
            field=models.BooleanField(default='1'),
            preserve_default=False,
        ),
    ]
