# Generated by Django 2.2.2 on 2019-08-24 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registercode',
            name='status',
        ),
        migrations.AlterField(
            model_name='registercode',
            name='code',
            field=models.CharField(db_index=True, max_length=20),
        ),
    ]
