# Generated by Django 2.2.2 on 2019-08-24 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0003_auto_20190824_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='final_login',
            field=models.DateTimeField(null=True),
        ),
    ]
