# Generated by Django 2.2.2 on 2019-08-24 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0004_auto_20190824_1926'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_name',
            new_name='user',
        ),
    ]
