# Generated by Django 2.2.2 on 2019-08-25 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0005_auto_20190824_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='type',
            field=models.IntegerField(null=True),
        ),
    ]
