# Generated by Django 2.2.2 on 2019-08-25 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0006_request_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='ps',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
