# Generated by Django 2.2.2 on 2019-08-25 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0008_requests'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='type',
            new_name='request_type',
        ),
    ]
